pipeline {
    agent any

    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'roshan', 
                    url: 'https://github.com/aitharoshankumar/festival.git', 
                    credentialsId: 'github-creds'
            }
        }

        stage('Check Directory') {
            steps {
                dir('react-31-1-26') {
                    sh 'pwd'
                    sh 'ls -la'
                    sh 'docker-compose version || docker compose version'
                }
            }
        }

        stage('Build Containers and Deploy Application') {
            steps {
                dir('react-31-1-26') {
                    sh 'docker compose down || true'
                    sh 'docker compose build'
                    sh 'docker compose up -d'
                }
            }
        }
    }
}
